name: Build and Release Go CLI Tool for Multiple Platforms

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - { os: "linux", goos: "linux", goarch: "amd64", ext: "" }
          - { os: "macos", goos: "darwin", goarch: "amd64", ext: "" }
          - { os: "windows", goos: "windows", goarch: "amd64", ext: ".exe" }
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # adjust to your required Go version

      - name: Build Binary for ${{ matrix.platform.os }}
        env:
          GOOS: ${{ matrix.platform.goos }}
          GOARCH: ${{ matrix.platform.goarch }}
        run: |
          go build -o dt-geo-converter${{ matrix.platform.ext }} .  # adjust the build command as needed

      - name: Upload Binary for ${{ matrix.platform.os }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: dt-geo-converter${{ matrix.platform.ext }}
          name: dt-geo-converter-${{ matrix.platform.os }}${{ matrix.platform.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
